### ISSUE TITLE
Message size exceeds limit with unhelpful errors

### ISSUE THREAD

**Issue by mayushii21** [No767/discord-ext-ipcx#31]
I spent a lot of time trying to understand why my IPC requests sometimes work and sometimes don't. The errors weren't very helpful. Anyway, here's what it is:

On line 140 of server.py `aiohttp.web.WebSocketResponse()` is set with the default `max_msg_size: int = 4 * 1024 * 1024`, and there is currently no way of changing this when setting up the IPC. In case of a large message size, this leads to the `message` in `websocket` to result in smth like this: `WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 4339841 exceeds limit 4194304'), extra=None)`, and that just goes into `message.json()` on line 144, which results in the not quite helpful error of `TypeError: the JSON object must be str, bytes or bytearray, not WebSocketError` being thrown. This then results in smth like `WSMessage(type=<WSMsgType.CLOSE: 8>, data=1009, extra='')` being received by `await websocket.receive()` on line 131 of client.py, which then goes into `recv.json()` on line 154 and, ofc, results in another unhelpful error: `TypeError: the JSON object must be str, bytes or bytearray, not int`.

**Comment by No767** [comment]
@mayushii21 max size is the default provided by aiohttp. 

Can you please share your **full** traceback instead? The errors you are showing aren't helpful for debugging 

I'm also not going to take the PR as of now as I want to fully understand the situation and address it with the proper fixes

**Comment by mayushii21** [comment]
@No767 here are the original tracebacks. You can reproduce it by trying to pass a large base64 encoded file, or anything that results in a size greater than the default `4*1024*1024` of aiohttp.

Client side:
```
Traceback (most recent call last):
  File "/workspace/dashboard-app/.venv/lib/python3.11/site-packages/sanic/app.py", line 1385, in handle_request
    response = await response
               ^^^^^^^^^^^^^^
  File "/workspace/dashboard-app/src/bot_dashboard/blueprints/giveaway.py", line 94, in start
    result = await req.app.ctx.ipc_client.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/dashboard-app/.venv/lib/python3.11/site-packages/discord/ext/ipcx/client.py", line 154, in request
    return recv.json()
           ^^^^^^^^^^^
  File "/workspace/dashboard-app/.venv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 121, in json
    return loads(self.data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int
```

Server side:
```
Traceback (most recent call last):
  File "/workspace/bot-app/.venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/bot-app/.venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/bot-app/.venv/lib/python3.11/site-packages/discord/ext/ipcx/server.py", line 144, in handle_accept
    request = message.json()
              ^^^^^^^^^^^^^^
  File "/workspace/bot-app/.venv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 121, in json
    return loads(self.data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not WebSocketError
```

The errors occur because of `WSMessage.data`, as mentioned above. Thanks for looking into it!

**Comment by No767** [comment]
@mayushii21 After some consideration, I've decided not to fix this. There are various issues with your approach, namely sending large base64 encoded files. ipcx is not designed to handle large unreasonable payloads such as the contents of an file (as this is an limitation of the websocket protocol itself). The best that I can do in this case is just to raise an error if the payload is too large. I would rather respect this known limit rather than to exploit said limit. 

In order to provide more depth on why I made this decision, I considered the proposed implementation, and many other factors. To me, this issue is extremely niche and as I only see this benefiting the author of this suggestion. If this is an issue amongst the masses, and can widely be replicated, then I would address this with an patch. But in this case, I decided not to as I can't see this benefiting others. Instead, I will more than likely in the future just throw an error for large payloads and hand the implementation of how they want to limit their payloads to be constrained around this. Thank you for considering and putting your contributions but ultimately for the sake of stability and other various factors, I've decided not to take this PR and address the issue.

I would also like to mention that the issue you are having is actually in regards to the size of your payloads, not the library itself. If you are curious on why it's erroring out, because of the large payload, AIOHTTP sends out an error and thus gives you an websocket error, which cannot be serialized to JSON format. Thus, it starts an whole chain of events, leading to that error that you have been mentioning about. The client-side error is a little bit interesting but I suspect that it is dependent on that original websocket error itself.

**Comment by mayushii21** [comment]
@No767 understood. Thank you for looking into it. If I do need to transfer relatively large files (~>15mb) tho, do you think it would be a bad or ok idea to use my "fix" of removing the limit? It seems to be working fine for me, for now at least. I don't really know much about this, so I don't know what issues to expect that might arise from this
